[workspace]
members = [
    "core/autograd",
    "core/network",

    "digits/infer_web",

    "digits/nn/infer",
    "digits/nn/train",
    "digits/nn/train_runner",

    "digits/dfdx/infer",
    "digits/dfdx/train",
]
