[package]
name = "autograd"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "val_bench"
harness = false

[[bench]]
name = "network_bench"
harness = false

[dev-dependencies]
float-cmp = "0.9.0"
criterion = "0.4.0"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
