[package]
name = "network"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "network_bench"
harness = false

[dev-dependencies]
criterion = "0.4.0"

[dependencies]
autograd = { path = "../autograd" }
rand = "0.8.5"
rand_distr = "0.4.3"
